name: Repo Migration from GitHub to GitHub
description: Perform a repository migration from GitHub to GitHub using GEI
title: "Repo Migration from GitHub to GitHub"
body:
  - type: textarea
    id: repositories
    attributes:
      label: Repository mappings
      description: Provide one mapping per line in the format `source-repo,target-repo`.
      placeholder: |
        sample-source-repo,sample-target-repo
        legacy-service,legacy-service
    validations:
      required: true
  - type: input
    id: github_source_organization
    attributes:
      label: GitHub source organization
      description: Provide the source GitHub organization login.
      placeholder: source-org
    validations:
      required: true
  - type: input
    id: github_target_organization
    attributes:
      label: GitHub target organization
      description: Provide the target GitHub organization login.
      placeholder: target-org
    validations:
      required: true
  - type: input
    id: ghe_subdomain
    attributes:
      label: GHE Subdomain (Optional)
      description: Provide the subdomain for the GHE instance (e.g., "my-subdomain" for https://api.my-subdomain.ghe.com).
      placeholder: my-subdomain
    validations:
      required: false
